AWSTemplateFormatVersion: 2010-09-09

Description: Valohai Private Workers resources

Parameters:
  AssumeRoleARN:
    Type: String
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    ap-northeast-1:
      AZs: 3
    ap-northeast-2:
      AZs: 4
    ap-northeast-3:
      AZs: 3
    ap-south-1:
      AZs: 3
    ap-southeast-1:
      AZs: 3
    ap-southeast-2:
      AZs: 3
    ca-central-1:
      AZs: 3
    eu-central-1:
      AZs: 3
    eu-west-1:
      AZs: 3
    eu-west-2:
      AZs: 3
    eu-west-3:
      AZs: 3
    eu-north-1:
      AZs: 3
    sa-east-1:
      AZs: 3
    us-east-1:
      AZs: 6
    us-east-2:
      AZs: 3
    us-west-1:
      AZs: 2
    us-west-2:
      AZs: 4

Resources: 
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AZs: !FindInMap [ RegionMap, !Ref "AWS::Region", AZs ]
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./network.yml

  Workers:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AssumeRoleARN: !Ref AssumeRoleARN
        VPC: !GetAtt Network.Outputs.VPC
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./workers.yml

  WorkerQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KeyPair: !Ref KeyPair
        Subnet: !GetAtt Network.Outputs.Subnet1
        VPC: !GetAtt Network.Outputs.VPC
        WorkersSecurityGroup: !GetAtt Workers.Outputs.SecurityGroup
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./worker-queue.yml

Outputs:
  KeyPair:
    Value: !Ref KeyPair
    Description: Key pair name

  PrivateIp:
    Value: !GetAtt WorkerQueue.Outputs.PrivateIp
    Description: Worker Queue instance private IP address

  PublicIp:
    Value: !GetAtt WorkerQueue.Outputs.PublicIp
    Description: Worker Queue instance public IP address

  Region:
    Value: !Ref AWS::Region

  ValohaiMasterRole:
    Value: !GetAtt Workers.Outputs.ValohaiMasterRoleArn
    Description: ValohaiMasterRole ARN

  VPC:
    Value: !GetAtt Network.Outputs.VPC
    Description: VPC ID
