AWSTemplateFormatVersion: 2010-09-09

Description: Valohai Private Workers resources

Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair that will be used for Valohai instances. You'll need to create this under EC2 -> KeyPairs before you can continue.

  QueueAddress:
    Type: String
    Description: Address of the Valohai queue that will be setup.

  ValohaiMasterRoleARN:
    Type: String
    Description: Name of the Valohai Master Role used for autoscaling resources.

Mappings:
  RegionMap:
    af-south-1:
      AZs: 3
      ImageId: ami-08a4b40f2fe1e4b35
    ap-east-1:
      AZs: 3
      ImageId: ami-0b215afe809665ae5
    ap-northeast-1:
      AZs: 3
      ImageId: ami-0df99b3a8349462c6
    ap-northeast-2:
      AZs: 4
      ImageId: ami-04876f29fd3a5e8ba
    ap-northeast-3:
      AZs: 3
      ImageId: ami-0001d1dd884af8872
    ap-south-1:
      AZs: 3
      ImageId: ami-0c1a7f89451184c8b
    ap-southeast-1:
      AZs: 3
      ImageId: ami-0d058fe428540cd89
    ap-southeast-2:
      AZs: 3
      ImageId: ami-0567f647e75c7bc05
    ca-central-1:
      AZs: 3
      ImageId: ami-0801628222e2e96d6
    eu-central-1:
      AZs: 3
      ImageId: ami-05f7491af5eef733a
    eu-south-1:
      AZs: 3
      ImageId: ami-018f430e4f5375e69
    eu-west-1:
      AZs: 3
      ImageId: ami-0a8e758f5e873d1c1
    eu-west-2:
      AZs: 3
      ImageId: ami-0194c3e07668a7e36
    eu-west-3:
      AZs: 3
      ImageId: ami-0f7cd40eac2214b37
    eu-north-1:
      AZs: 3
      ImageId: ami-0ff338189efb7ed37
    me-south-1:
      AZs: 3
      ImageId: ami-0eddb8cfbd6a5f657
    sa-east-1:
      AZs: 3
      ImageId: ami-054a31f1b3bf90920
    us-east-1:
      AZs: 6
      ImageId: ami-09e67e426f25ce0d7
    us-east-2:
      AZs: 3
      ImageId: ami-00399ec92321828f5
    us-west-1:
      AZs: 2
      ImageId: ami-0d382e80be7ffdae5
    us-west-2:
      AZs: 4
      ImageId: ami-03d5c68bab01f3496

Resources: 
  Network:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      Parameters:
        AZs: !FindInMap [ RegionMap, !Ref "AWS::Region", AZs ]
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./network.yml

  S3Bucket:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      Parameters:
        ValohaiMasterRoleARN: !Ref ValohaiMasterRoleARN
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./s3bucket.yml

  WorkerQueue:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      Parameters:
        ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", ImageId ]
        KeyPair: !Ref KeyPair
        QueueAddress: !Ref QueueAddress
        Subnet: !GetAtt Network.Outputs.Subnet1
        VPC: !GetAtt Network.Outputs.VPC
        WorkersSecurityGroup: !GetAtt Network.Outputs.SecurityGroup
      Tags:
        - Key: valohai
          Value: "1"
      TemplateURL: ./worker-queue.yml

Outputs:
  KeyPair:
    Value: !Ref KeyPair
    Description: Key pair name

  PrivateIp:
    Value: !GetAtt WorkerQueue.Outputs.PrivateIp
    Description: Worker Queue instance private IP address

  PublicIp:
    Value: !GetAtt WorkerQueue.Outputs.PublicIp
    Description: Worker Queue instance public IP address

  Region:
    Value: !Ref AWS::Region

  ValohaiMasterRole:
    Value: !Ref ValohaiMasterRoleARN
    Description: ValohaiMasterRole ARN

  VPC:
    Value: !GetAtt Network.Outputs.VPC
    Description: VPC ID
