AWSTemplateFormatVersion: 2010-09-09

Description: Basic network for Valohai resources

Parameters:
  AZs:
    Description: Amount of availability zones in this region, i.e. amount of subnets to create
    Type: Number
    Default: 2

Conditions:
  CreateSixSubnets: !Equals
    - !Ref AZs
    - 6
  CreateFiveSubnets: !Or
    - !Condition CreateSixSubnets
    - !Equals
      - !Ref AZs
      - 5
  CreateFourSubnets: !Or
    - !Condition CreateFiveSubnets
    - !Equals
      - !Ref AZs
      - 4
  CreateThreeSubnets: !Or
    - !Condition CreateFourSubnets
    - !Equals
      - !Ref AZs
      - 3

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.6/16
      Tags:
        - Key: Name
          Value: valohai-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: valohai-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  Subnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}a"
        CidrBlock: 10.0.0.0/20
        InternetGateway: !Ref InternetGateway
        Number: 1
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml

  Subnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}b"
        CidrBlock: 10.0.16.0/20
        InternetGateway: !Ref InternetGateway
        Number: 2
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml

  Subnet3:
    Type: AWS::CloudFormation::Stack
    Condition: CreateThreeSubnets
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}c"
        CidrBlock: 10.0.32.0/20
        InternetGateway: !Ref InternetGateway
        Number: 3
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml
  
  Subnet4:
    Type: AWS::CloudFormation::Stack
    Condition: CreateFourSubnets
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}d"
        CidrBlock: 10.0.48.0/20
        InternetGateway: !Ref InternetGateway
        Number: 4
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml
  
  Subnet5:
    Type: AWS::CloudFormation::Stack
    Condition: CreateFiveSubnets
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}e"
        CidrBlock: 10.0.64.0/20
        InternetGateway: !Ref InternetGateway
        Number: 5
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml

  Subnet6:
    Type: AWS::CloudFormation::Stack
    Condition: CreateSixSubnets
    Properties:
      Parameters:
        AvailabilityZone: !Sub "${AWS::Region}f"
        CidrBlock: 10.0.80.0/20
        InternetGateway: !Ref InternetGateway
        Number: 6
        VPC: !Ref VPC
      TemplateURL: ./subnet.yml

Outputs:
  Subnet1:
    Value: !GetAtt Subnet1.Outputs.Subnet

  VPC:
    Value: !Ref VPC
